services:
  exam-crafters-api:
    build:
      context: ./exam-crafter-api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./exam-crafter-api/src:/app/src
    environment:
      MONGODB_URL: ${MONGODB_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  exam-crafters:
    build:
      context: ./exam-crafter
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./exam-crafter/src:/app/src
    environment:
      NEXT_PUBLIC_PRODUCTION_API_URL: https://exam-crafter.up.railway.app
      MONGODB_URL: ${MONGODB_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_ANALYTICS_KEY: ${GOOGLE_ANALYTICS_KEY}
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGODB_URL: ${MONGODB_URL}

volumes:
  mongo_data: